In [1]:
import numpy as np
from scipy import sparse

matrix = np.array([[0,0,0,0,0,0,0,0,0,0],
[0,1,0,0,0,0,0,0,0,0],
[3,0,0,0,0,0,0,0,0,0]]) # 값이 다 채워져 있는 밀집행렬(dense array)
print(matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [2]:
# 0이 아닌 원소만 저장하는 행렬

matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [3]:
matrix_sparse_2 = sparse.csr_matrix(([1,3],([1,2],[1,0])), shape=(3,10)) # 값 1은 1행 1열에, 값 3은 2행 0열에 들어가고 전체 행렬은 3행 10열
print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [4]:
print(matrix_sparse_2.toarray()) # 희소행렬을 밀집행렬로 바꾸는 toarray()

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [5]:
import numpy as np
matrix = np.array([[1,2,3,4],
[5,6,7,8],
[9,10,11,12]])
matrix.shape

(3, 4)

In [6]:
matrix.size # 행렬의 원소 개수 확인 (행*열)

12

In [7]:
matrix.ndim # 차원 수 확인

2

In [8]:
print(matrix.dtype) # 원소의 데이터 타입 확인
print(matrix.itemsize) # 원소 하나가 차지하는 바이트 크기 확인
print(matrix.nbytes) # 배열 전체가 차지하는 바이트 크기 확인

int32
4
48


In [9]:
matrix.flatten() # 1차원으로 변환

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
import pandas as pd

url = 'https://tinyurl.com/simulated-excel'
df = pd.read_excel(url, sheet_name=0, header=1)
df.head(2)

5 2015-01-01 00:00:00  0
0  5 2015-01-01 00:00:01  0
1  9 2015-01-01 00:00:02  0

In [13]:
url = 'https://tinyurl.com/simulated-json'
df = pd.read_json(url)
df.head(2)

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0

In [15]:
import pandas as pd
from sqlalchemy import create_engine

conn = create_engine('sqlite:///c:/data/db/product.db')
df = pd.read_sql_query('SELECT * FROM product', conn)
df.head(2)

id product_name    price  amount
0   1          냉장고  1000000       5

In [16]:
import pandas as pd

url = 'c:/data/titanic/train2.csv'
df = pd.read_csv(url)
df[df['Sex']=='female'].head(2)

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [17]:
df[(df['Sex']=='female')&(df['Age']>=60)]

PassengerId  Survived  Pclass  \
275          276         1       1   
366          367         1       1   
483          484         1       3   
829          830         1       1   

                                                 Name     Sex   Age  SibSp  \
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  female  60.0      1   
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   

     Parch  Ticket     Fare Cabin Embarked  
275      0   13502  77.9583    D7        S  
366      0  110813  75.2500   D37        C  
483      0    4134   9.5875   NaN        S  
829      0  113572  80.0000   B28      NaN

In [18]:
df['Sex'].replace("female", "Woman").head(2)

0     male
1    Woman
Name: Sex, dtype: object

In [19]:
df['Sex'].replace(["female", "male"], ["Woman", "Man"]).head(5)

0      Man
1    Woman
2    Woman
3    Woman
4      Man
Name: Sex, dtype: object

In [20]:
df.replace(1, "One").head(2)

PassengerId Survived Pclass  \
0         One        0      3   
1           2      One    One   

                                                Name     Sex   Age SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0   One   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   One   

  Parch     Ticket     Fare Cabin Embarked  
0     0  A/5 21171   7.2500   NaN        S  
1     0   PC 17599  71.2833   C85        C

In [21]:
df.replace({"female":1, "male":0}).head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [22]:
df.rename(columns={'PassengerId':'id'}).head()

id  Survived  Pclass                                               Name  \
0   1         0       3                            Braund, Mr. Owen Harris   
1   2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2   3         1       3                             Heikkinen, Miss. Laina   
3   4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4   5         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [23]:
for name in df['Name'][0:2]:
    print(name.upper())

BRAUND, MR. OWEN HARRIS
CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER)


In [24]:
for i, row in df.iterrows():
    print(i)
    print(row[0])
    print(row[1])

0
1
0
1
2
1
2
3
1
3
4
1
4
5
0
5
6
0
6
7
0
7
8
0
8
9
1
9
10
1
10
11
1
11
12
1
12
13
0
13
14
0
14
15
0
15
16
1
16
17
0
17
18
1
18
19
0
19
20
1
20
21
0
21
22
1
22
23
1
23
24
1
24
25
0
25
26
1
26
27
0
27
28
0
28
29
1
29
30
0
30
31
0
31
32
1
32
33
1
33
34
0
34
35
0
35
36
0
36
37
1
37
38
0
38
39
0
39
40
1
40
41
0
41
42
0
42
43
0
43
44
1
44
45
1
45
46
0
46
47
0
47
48
1
48
49
0
49
50
0
50
51
0
51
52
0
52
53
1
53
54
1
54
55
0
55
56
1
56
57
1
57
58
0
58
59
1
59
60
0
60
61
0
61
62
1
62
63
0
63
64
0
64
65
0
65
66
1
66
67
1
67
68
0
68
69
1
69
70
0
70
71
0
71
72
0
72
73
0
73
74
0
74
75
1
75
76
0
76
77
0
77
78
0
78
79
1
79
80
1
80
81
0
81
82
1
82
83
1
83
84
0
84
85
1
85
86
1
86
87
0
87
88
0
88
89
1
89
90
0
90
91
0
91
92
0
92
93
0
93
94
0
94
95
0
95
96
0
96
97
0
97
98
1
98
99
1
99
100
0
100
101
0
101
102
0
102
103
0
103
104
0
104
105
0
105
106
0
106
107
1
107
108
1
108
109
0
109
110
1
110
111
0
111
112
0
112
113
0
113
114
0
114
115
0
115
116
0
116
117
0
117
118
0
118
119
0
119
120
0
120
121
0
121
122


In [25]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples=10, n_features=2, centers=1, random_state=1) # 모의 데이터 생성
features[0,0] = 10000
features[0,1] = 10000 # 첫 번째 샘플을 이상치로 변경

In [26]:
# 이상치 감지 객체 설정
# contamination은 이상치의 예상 비율

outlier_detector = EllipticEnvelope(contamination=0.1)

In [27]:
outlier_detector.fit(features) # 이상치 감지 객체 훈련

EllipticEnvelope()

In [28]:
outlier_detector.predict(features) # -1이 이상치, 1이 정상 샘플

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [29]:
feature = features[:,0]

def indicies_of_outliers(x):
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1
    lower_bound = q1 - (iqr * 1.5)
    upper_bound = q3 + (iqr * 1.5)
    return np.where((x > upper_bound) | (x < lower_bound))

indicies_of_outliers(feature)

(array([0], dtype=int64),)

In [31]:
import pandas as pd

houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]
houses

Price  Bathrooms  Square_Feet
0   534433        2.0         1500
1   392333        3.5         2500
2   293222        2.0         1500
3  4322032      116.0        48000

In [32]:
import numpy as np

houses["Outlier"] = np.where(houses["Bathrooms"]<20, 0, 1)
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

In [33]:
# 이상치의 영향이 줄어들도록 특성을 변환함. 로그 특성을 활용

houses["Log_Of_Square_Feet"] = [np.log(x) for x in houses["Square_Feet"]]
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

In [34]:
# 특성 이산화

import numpy as np
from sklearn.preprocessing import Binarizer

age = np.array([[6], [12], [20], [36], [65]])
binarizer = Binarizer(threshold=18) # 18세를 기준으로 0, 1로 구분

binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [35]:
np.digitize(age, bins=[20, 30, 64]) # 20, 30, 64를 기준으로 4개로 구분

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

In [36]:
np.digitize(age, bins=[20, 30, 64], right=True) # 마지막 숫자를 구간에 포함시킴

array([[0],
       [0],
       [0],
       [2],
       [3]], dtype=int64)

In [37]:
np.digitize(age, bins=[18]) # 18을 기준으로 0, 1로 구분

array([[0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)

In [38]:
from sklearn.preprocessing import KBinsDiscretizer

kb = KBinsDiscretizer(3, encode='ordinal', strategy='quantile')
print(kb.fit_transform(age))
print(kb.bin_edges_) # 구간 정보

[[0.]
 [0.]
 [1.]
 [2.]
 [2.]]
[array([ 6.        , 14.66666667, 30.66666667, 65.        ])]


In [39]:
kb = KBinsDiscretizer(4, encode='onehot-dense', strategy='quantile')
kb.fit_transform(age)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [40]:
kb = KBinsDiscretizer(4, encode='onehot-dense', strategy='uniform') # 동일한 길이로 구간을 나누어서 원핫인코딩
kb.fit_transform(age)

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
kb.bin_edges_

array([array([ 6.  , 20.75, 35.5 , 50.25, 65.  ])], dtype=object)

In [43]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

features, _ = make_blobs(n_samples=50, n_features=2, centers=3, random_state=1)
df = pd.DataFrame(features, columns=["feature_1", "feature_2"])
clusterer = KMeans(3, random_state=0)
clusterer.fit(features)
df["group"] = clusterer.predict(features)
df.head()

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2